---
title: "SAGESA Research and Training Network Activities"
---

## Establishment of the SAGESA Research and Training Network

In 2021, the SAGESA project established a research and training network, to facilitate capacity building for pathogen genomics and surveillance of anti-microbial resistance (AMR) in Africa. The SAGESA project is funded by the Cambridge Africa ALBORADA Research Fund, and is a collaboration by scientists from the National Institute of Communicable Diseases in South Africa, the Faculty of Medicine and Health Sciences, University of Zimbabwe, Wellcome Connecting Science and the Centre for Genomic Pathogen Surveillance.

## Project goal

The goal of this project was to establish a peer network platform which provides access to training and expertise to scientists interested in genomics of disease pathogens and surveillance of antimicrobial resistance (AMR).

## Objectives

● Establish the training and research network for genomic surveillance of AMR in Africa

● Provide training for bioinformatics in AMR genomics in the SADC region

● Establish collaborative research and training projects for AMR surveillance

## Target audience

Scientists based anywhere in the world interested in developing skills and resources for AMR genomics in Africa and globally.

## Joining the network

To join the network simply contact us or access an online form for providing basic personal information, country of origin and consent for use of media for promotional purposes by the collaborating organisations.

THE SAGESA Core Team developed activities encompassing virtual meetings and training and facilitated a network of scientists interested in sharing knowledge and skills i n genomics of antimicrobial resistance (AMR) Africa.

The SAGESA launch meeting, held in November 2021, facilitated the introduction of initial network members - approximately 50 at the time. This was followed by a needs assessment workshop to explore network, research and training needs in Africa.

## Workshop objectives

● Official launch of SAGESA Network - the first Africa AMR genomics research and

training network.

● Discuss needs and gaps within the region with regards to application of

genomics for AMR surveillance - a focus on training needs and network development.

● Provide an overview of the planned/proposed SAGESA activities and discuss the future of the network.

A virtual hybrid model used live discussion of topics and the Padlet platform where participants provided detailed information about - the current status of training and research, training needs and research interests, and expectations of SAGESA network.
